### PR TITLE
TKT-1 TKT-3 Update index.html

### PR DESCRIPTION
**Pull request by schneekatze**
Description to the ticket

### CODE REVIEW

**Comment by schneekatze** [comment]
Comment

**Comment by schneekatze** [comment]
Obsolete approve with the comment

**Comment by schneekatze** [comment]
Another one

**Comment by nikolai-billie** [comment]
test

**Comment by nikolai-billie** [comment]
Comment

**Comment by nikolai-billie** [comment]
test

**Comment by nikolai-billie** [comment]
The comment

**Pull request closed without merging**
